'use client';

import { useState, useMemo, lazy, Suspense, memo } from 'react';
import { Search, Loader2, AlertCircle } from 'lucide-react';
import { generateSampleComMockData, generateDefaultMockData, generateMockResult } from '../lib/mockData';
import { AuditResult } from '../types/audit';
import { downloadReportAsHTML, openReportForPrint } from '../components/ReportGenerator';

// Lazy load heavy components to reduce initial bundle size
const AuditFindingCard = lazy(() => import('../components/AuditFindingCard'));
const SummaryCard = lazy(() => import('../components/SummaryCard'));
const FilterDropdown = lazy(() => import('../components/FilterDropdown'));

export default function Home() {
  const [url, setUrl] = useState('');
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<AuditResult | null>(null);
  const [error, setError] = useState('');
  const [filterCategory, setFilterCategory] = useState<string>('all');
  const [filterSeverity, setFilterSeverity] = useState<string>('all');
  const [expandedFindings, setExpandedFindings] = useState<Set<number>>(new Set());

  // Mock data generation moved to lib/mockData.ts to prevent recreation on every render
  const generateMockData = (url: string): AuditResult => {
    const normalizedUrl = url.startsWith('http') ? url : `https://${url}`;
    const urlLower = normalizedUrl.toLowerCase();
    
    // Check if URL is sample.com and use specific mock data
    if (urlLower.includes('sample.com')) {
      const mockFindings = generateSampleComMockData();
      return generateMockResult(normalizedUrl, mockFindings);
    }
    
    // Default mock data for example.com and other URLs
    const mockFindings = generateDefaultMockData();
    return generateMockResult(normalizedUrl, mockFindings);
  };
      // ACCESSIBILITY - All Severities

  const handleAudit = async () => {
    if (!url.trim()) {
      setError('Please enter a URL');
      return;
    }

    setLoading(true);
    setError('');
    setResult(null);
    setExpandedFindings(new Set());

    try {
      const response = await fetch('/api/audit', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ url }),
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error || 'Audit failed');
      }

      setResult(data);
    } catch (err: any) {
      setError(err.message || 'Failed to perform audit');
    } finally {
      setLoading(false);
    }
  };

  const toggleFinding = (index: number) => {
    const newExpanded = new Set(expandedFindings);
    if (newExpanded.has(index)) {
      newExpanded.delete(index);
    } else {
      newExpanded.add(index);
    }
    setExpandedFindings(newExpanded);
  };

  const filteredFindings = useMemo(() => {
    if (!result) return [];
    return result.findings.filter(finding => {
      const categoryMatch = filterCategory === 'all' || finding.category === filterCategory;
      const severityMatch = filterSeverity === 'all' || finding.severity === filterSeverity;
      return categoryMatch && severityMatch;
    });
  }, [result, filterCategory, filterSeverity]);


  const generateShareableReport = () => {
    if (!result) return '';

    const report = `
UX AUDIT REPORT
================

Website: ${result.url}
Date: ${new Date(result.timestamp).toLocaleString()}
Overall Score: ${result.summary.overallScore}/100

SUMMARY
-------
Total Issues: ${result.summary.totalIssues}
  - Critical: ${result.summary.critical}
  - High: ${result.summary.high}
  - Medium: ${result.summary.medium}
  - Low: ${result.summary.low}

By Category:
  - Accessibility: ${result.summary.accessibility}
  - Usability: ${result.summary.usability}
  - Design: ${result.summary.design}
  - Performance: ${result.summary.performance}
  - SEO: ${result.summary.seo}

DETAILED FINDINGS
-----------------
${result.findings.map((finding, index) => `
${index + 1}. ${finding.issue.toUpperCase()}
   Category: ${finding.category} | Severity: ${finding.severity}
   Location: ${finding.location}
   
   Description: ${finding.description}
   
   Suggestion: ${finding.suggestion}
   ${finding.codeSnippet ? `\n   Code Example:\n   ${finding.codeSnippet}` : ''}
`).join('\n')}

---
Generated by AI UX Audit Agent
Report ID: ${result.timestamp}
    `.trim();

    return report;
  };

  const downloadReport = () => {
    if (!result) return;
    downloadReportAsHTML(result);
  };

  const shareReport = async () => {
    if (!result) return;
    // Open report in new window for printing/PDF
    openReportForPrint(result);
  };

  return (
    <div className="min-h-screen bg-[#0a1628]">
      <div className="container mx-auto px-4 py-8 max-w-7xl">
        {/* Header */}
        <div className="text-center mb-12">
          <h1 className="text-5xl font-bold text-white mb-4">
            AI UX Audit Agent
          </h1>
          <p className="text-xl text-gray-300 max-w-2xl mx-auto">
            Automated UX analysis powered by AI. Get instant insights on accessibility, 
            usability, design consistency, and more.
          </p>
        </div>

        {/* Input Section */}
        <div className="bg-[#1a2332] rounded-2xl shadow-xl p-8 mb-8 border border-gray-700/50">
          <div className="flex gap-4">
            <div className="flex-1">
              <input
                type="text"
                value={url}
                onChange={(e) => setUrl(e.target.value)}
                onKeyPress={(e) => e.key === 'Enter' && !loading && handleAudit()}
                placeholder="Enter website URL (e.g., example.com or https://example.com)"
                className="w-full px-6 py-4 text-lg bg-[#0a1628] border-2 border-gray-600 rounded-xl text-white placeholder-gray-400 focus:outline-none focus:border-teal-500 focus:ring-2 focus:ring-teal-500/20"
                disabled={loading}
              />
            </div>
            <button
              onClick={handleAudit}
              disabled={loading}
              className="px-8 py-4 bg-[#14b8a6] text-white rounded-xl font-semibold hover:bg-[#0d9488] disabled:bg-teal-800 disabled:cursor-not-allowed transition-colors flex items-center gap-2 shadow-lg"
            >
              {loading ? (
                <>
                  <Loader2 className="animate-spin" size={20} />
                  Analyzing...
                </>
              ) : (
                <>
                  <Search size={20} />
                  Audit Website
                </>
              )}
            </button>
          </div>
          {error && (
            <div className="mt-4 p-4 bg-red-900/30 border border-red-500/50 rounded-lg flex items-center gap-2 text-red-300">
              <AlertCircle size={20} />
              <span>{error}</span>
            </div>
          )}
        </div>

        {/* Results */}
        {result && (
          <div className="space-y-6">
            {/* Summary Card */}
            <Suspense fallback={<div className="bg-[#1a2332] rounded-2xl p-8 animate-pulse">Loading summary...</div>}>
              <SummaryCard
                result={result}
                onShare={shareReport}
                onDownload={downloadReport}
              />
            </Suspense>

            {/* Findings */}
            <div className="bg-[#1a2332] rounded-2xl shadow-xl p-8 border border-gray-700/50">
              <Suspense fallback={<div className="animate-pulse">Loading filters...</div>}>
                <FilterDropdown
                  filterCategory={filterCategory}
                  filterSeverity={filterSeverity}
                  onCategoryChange={setFilterCategory}
                  onSeverityChange={setFilterSeverity}
                  filteredCount={filteredFindings.length}
                />
              </Suspense>

              {filteredFindings.length === 0 ? (
                <div className="text-center py-12">
                  <p className="text-gray-400">No findings match the selected filters.</p>
                  <button
                    onClick={() => {
                      setFilterCategory('all');
                      setFilterSeverity('all');
                    }}
                    className="mt-4 px-4 py-2 bg-teal-600 text-white rounded-lg hover:bg-teal-700 transition-colors"
                  >
                    Clear Filters
                  </button>
                </div>
              ) : (
                <Suspense fallback={<div className="space-y-4"><div className="animate-pulse h-32 bg-[#0a1628] rounded-xl"></div></div>}>
                  <div className="space-y-4">
                    {filteredFindings.map((finding, index) => {
                      const originalIndex = result.findings.indexOf(finding);
                      const isExpanded = expandedFindings.has(originalIndex);
                      return (
                        <AuditFindingCard
                          key={originalIndex}
                          finding={finding}
                          index={originalIndex}
                          isExpanded={isExpanded}
                          onToggle={() => toggleFinding(originalIndex)}
                        />
                      );
                    })}
                  </div>
                </Suspense>
              )}
            </div>
          </div>
        )}

        {/* Footer */}
        <div className="text-center mt-12 text-gray-400">
          <p>Powered by AI • Built for Lunim Studio</p>
        </div>
      </div>
    </div>
  );
}
